### PR TITLE
Update qr_detection.py |‌Change the QR code reading to accept additional "unknown" values

### PR DESCRIPTION
**Pull request by BDadmehr0**
This template expects four specific values in the QR code: two floating point numbers and two integers.

### CODE REVIEW

**Comment by BDadmehr0** [comment]
> This template expects four specific values in the QR code: two floating point numbers and two integers.

برای تغییر تابع خواندن کد QR برای پذیرش مقادیر "ناشناخته" اضافی

**Comment by BDadmehr0** [comment]
> why do we need this?

To modify the QR code reading function to accept additional "unknown" values

**Comment by adsau59** [comment]
> > why do we need this?
> 
> 
> 
> To modify the QR code reading function to accept additional "unknown" values

Does this currently cause issue in fishy?

**Comment by BDadmehr0** [comment]
> > > why do we need this?
> > 
> > 
> > 
> > To modify the QR code reading function to accept additional "unknown" values
> 
> Does this currently cause issue in fishy?

Yes, most likely

**Comment by adsau59** [comment]
> > > > why do we need this?
> > > 
> > > 
> > > To modify the QR code reading function to accept additional "unknown" values
> > 
> > 
> > Does this currently cause issue in fishy?
> 
> Yes, most likely

what do u mean by most likely? if it does cause issue, can u send some screenshot/logs for the error which this pr intends to solve?... I still dont see what this PR is intending to solve

Ideally there should be an issue created explaining what the issue is before PR is created

**Comment by BDadmehr0** [comment]
I was sure that an issue related to **Change the QR code reading to accept additional "unknown" values**
It was there, but it is not anymore. It doesn't matter anymore

**Pull request closed without merging**
